Slips:
  # DO NOT use spaces in the version
  version: 1.0.13

Suricata:
  # DO NOT use spaces in the version
  version: 7.0.4_RELEASE


Params:
  # in seconds
  # 1h = 3600
  # 2h = 7200
  # 30min = 1800
  timewindow_width: 3600