import argparse


class ArgsParser:
    parser = argparse.ArgumentParser(description='Process command line arguments.')
    parser.add_argument('-s', '--slips_sqlite_db',  required=False, dest='slips_db', help='sqlite db generated by Slips')
    parser.add_argument('-e', '--eve',  required=False, dest='eve_file', help='eve.json file of Suricata')

    parser.add_argument('-gtd', '--ground_truth_dir', required=False,  dest='ground_truth_dir', help='Ground truth labeled Zeek directory')
    parser.add_argument('-gtf', '--ground_truth_file', required=False,  dest='ground_truth_file', help='Ground truth labeled Zeek conn.log file.')

    parser.add_argument('-cm', '--confusion_matrix', required=False,  dest='confusion_matrix_db', help='Confusion matrix db with TP, TN, FP, FN of each tool')

    args = parser.parse_args()
